
###############################################################################
#
# Inclusive Makefile for the cjson_util module.
#
# Autogenerated 2014-05-23 13:07:47.664253
#
###############################################################################
cjson_util_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(cjson_util_BASEDIR)/module/make.mk
include $(cjson_util_BASEDIR)/module/auto/make.mk
include $(cjson_util_BASEDIR)/module/src/make.mk
include $(cjson_util_BASEDIR)/utest/_make.mk

