
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-10-02 14:24:50.279852
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
OS_BASEDIR := $(BASEDIR)OS
VPI_BASEDIR := $(BASEDIR)VPI
IOF_BASEDIR := $(BASEDIR)IOF
FME_BASEDIR := $(BASEDIR)FME
uCli_BASEDIR := $(BASEDIR)uCli
cjson_BASEDIR := $(BASEDIR)cjson
PPE_BASEDIR := $(BASEDIR)PPE
murmur_BASEDIR := $(BASEDIR)murmur
BigList_BASEDIR := $(BASEDIR)BigData/BigList


ALL_MODULES := $(ALL_MODULES) uCli PPE cjson OS murmur BigList IOF FME VPI
