###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := slot_allocator
AUTOMODULE := slot_allocator
include $(BUILDER)/definemodule.mk
