
###############################################################################
#
# Inclusive Makefile for the timer_wheel module.
#
# Autogenerated 2014-01-31 14:53:27.773369
#
###############################################################################
timer_wheel_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(timer_wheel_BASEDIR)/module/make.mk
include $(timer_wheel_BASEDIR)/module/auto/make.mk
include $(timer_wheel_BASEDIR)/module/src/make.mk
include $(timer_wheel_BASEDIR)/utest/_make.mk

