
###############################################################################
#
# Inclusive Makefile for the pimu module.
#
# Autogenerated 2013-10-08 14:42:11.849251
#
###############################################################################
pimu_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(pimu_BASEDIR)/module/make.mk
include $(pimu_BASEDIR)/module/auto/make.mk
include $(pimu_BASEDIR)/module/src/make.mk
include $(pimu_BASEDIR)/utest/_make.mk

