###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := snmp_subagent
AUTOMODULE := snmp_subagent
include $(BUILDER)/definemodule.mk
