
###############################################################################
#
# Inclusive Makefile for the snmp_subagent module.
#
# Autogenerated 2015-08-05 21:38:45.508283
#
###############################################################################
snmp_subagent_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(snmp_subagent_BASEDIR)/module/make.mk
include $(snmp_subagent_BASEDIR)/module/auto/make.mk
include $(snmp_subagent_BASEDIR)/module/src/make.mk
include $(snmp_subagent_BASEDIR)/utest/_make.mk

