
###############################################################################
#
# Inclusive Makefile for the debug_counter module.
#
# Autogenerated 2014-03-18 14:04:32.819258
#
###############################################################################
debug_counter_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(debug_counter_BASEDIR)/module/make.mk
include $(debug_counter_BASEDIR)/module/auto/make.mk
include $(debug_counter_BASEDIR)/module/src/make.mk
include $(debug_counter_BASEDIR)/utest/_make.mk

