###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := debug_counter
AUTOMODULE := debug_counter
include $(BUILDER)/definemodule.mk
